config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  devise_for :users, :skip => [:registrations] 
    as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  root 'welcome#index'
  resources :songs
  get '/finish_song', to: 'songs#finish_song', as: 'finish_song'
  get '/skip_song', to: 'songs#skip_song', as: 'skip_song'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
    scope :finished, -> { where( finished: true ) }
    scope :upcoming, -> { where( finished: false, skipped: false ) }
    scope :postponed, -> { where( finished: false, postponed: true ) }
    scope :skipped, -> { where( finished: false, skipped: true ) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :set_song, only: %i[ destroy edit finish_song show skip_song update ]

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)
    respond_to do |format|
      if @song.save
        format.html { redirect_to songs_url, notice: "A song was created for #{ @song.performer }." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: "#{@performer}'s song was removed." }
      format.json { head :no_content }
    end
  end

  # GET /songs/1/edit
  def edit
  end

  # method to click a button and finish a song
  def finish_song 
    if @song.update( finished: true ) 
      redirect_to songs_url, notice: "#{ @song.performer } just finished a song." 
    else 
      redirect_to songs_url, error: "#{ @song.performer }'s song was not finished."
    end
  end

  # GET /songs
  def index
    @finished = Song.finished
    @postponed = Song.postponed
    @skipped = Song.skipped
    @song = Song.new
    @songs = Song.all
    @upcoming = Song.upcoming
  end
  
  # method to click a button and skip a song
  def skip_song 
    skipped = !@song.skipped 
    if @song.update( skipped: skipped ) 
      redirect_to songs_url, notice: "#{ @song.performer } just skipped a song." 
    else 
      redirect_to songs_url, error: "#{ @song.performer }'s song was not skipped."
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to songs_url, notice: "#{@performer}'s song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /songs/1 
  def show
  end

  private

  def set_song
    @song = Song.find( params[ :id ] )
  end
    
  def song_params
    params.require( :song ).permit(
      :category, 
      :finished, 
      :performer, 
      :postponed, 
      :url, 
      :skipped
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/song_helper.rb
module SongHelper 
  def link_to_edit( song )
    link_to(edit_song_path(song), class: "song-action btn-discreet") do
      render partial: "components/icons/edit"
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Karaoke QUEUE
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = favicon_link_tag asset_path('favicon.svg')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/songs/_button_action_song.html.haml
- if action == "finish"
  = link_to song.url, onclick: "takeActionOnSong(this)", class: "btn discreet", data:{ action: action, id: song.id }, title: action, target: "_blank" do
    %span 
      = render "components/icons/play"
- elsif action == "skip"
  %button{onClick: "takeActionOnSong(this)", class: "btn discreet", data:{ action: action, id: song.id }, title: song.skipped ? "resume" : "skip"}
    - if song.skipped 
      %span 
        = render "components/icons/add"
    - else 
      %span 
        = render "components/icons/skip"
- elsif action == "edit"
  = link_to edit_song_path(song), class: "btn discreet", title: action do
    %span
      = render "components/icons/edit"
- else 
  = button_to song, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn discreet", title: action do
    %span 
      = render "components/icons/destroy"

app/views/songs/_form.html.haml
= form_with(model: song, local: true) do |form|
  - if song.errors.any?
    #error_explanation
      %h2
        = pluralize(song.errors.count, "error")
        prohibited this song from being saved:
      %ul
        - song.errors.full_messages.each do |message|
          %li= message
  = label_tag do
    Performer
    \#{form.text_field :performer}
  = label_tag do
    Category
    \#{form.text_field :category}
  = label_tag do
    URL
    \#{form.text_field :url}
  - unless index_page
    = label_tag do
      Skipped
      \#{form.check_box :skipped}
  - unless index_page
    = label_tag do
      Finished
      \#{form.check_box :finished}
  .actions
    = form.submit "Queue Song"

app/views/songs/_index_form.html.haml
= form_for( song ) do |s|
  %tr
    %td= link_to song.performer, song
    - if upcoming
      %td
        = render "button_action_song", action: "finish", song: @upcoming[ 0 ]
    - else
      %td
    - [ "skip", "edit", "destroy" ].each do | action | 
      %td 
        = render "button_action_song", action: action, song: song




:javascript 
  function takeActionOnSong( element ) {
    let data = element.dataset;
    let action = data.action;
    let id = data.id;
    fetch(`/${action}_song?id=${id}`, {
      method: 'get',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      }
    })
    .then(response => response.json())
    .then(response => console.log(JSON.stringify(response)))
    .then(response => location.reload());
  };

app/views/songs/_table_headers.html.haml
%thead
  %tr
    %td
    %td performer
    %td skipped
    %td
    %td

app/views/songs/edit.html.haml
%h1 Editing Song
= render 'form', song: @song, index_page: false
= link_to 'Show', @song
|
= link_to 'Back', songs_path

app/views/songs/index.html.haml
%h1 KARAOKE QUEUE
%h2 Queue A New Song
= render 'form', song: @song, index_page: true
%br/
%br/
%h2 Upcoming Performers
%table
  %tbody
    - if @upcoming[ 0 ]
      = render 'index_form', song: @upcoming[ 0 ], upcoming: true
    - if @upcoming[ 1.. ]
      - @upcoming[ 1.. ].each do | song |
        = render 'index_form', song: song, upcoming: false
    - @skipped.each do | song |
      = render 'index_form', song: song, upcoming: false
%br/
%h2 Finished Performers
%table
  %tbody
    - @finished.each do |song|
      = render 'index_form', song: song, upcoming: false
%br/

app/views/songs/new.html.haml
%h1 New Song
= render 'form', song: @song, index_page: false
= link_to 'Back', songs_path

app/views/songs/show.html.haml
= @song.performer
= @song.url
= @song.skipped
= link_to 'Edit', edit_song_path(@song)
|
= link_to 'Back', songs_path

app/views/welcome/index.html.haml
%h1 KARAOKE QUEUE
%div{ style: "margin-top: 1rem; "}
- if user_signed_in?
  = link_to "Go To Songs", songs_path
  = button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn discreet", style: "margin-top: 1rem;"
- else
  = button_to "Sign in", new_user_session_path, class: "btn discreet"